name: push_start

on:
  push:
    branches:
      - main

jobs:
  convert_env:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.convert.outputs.env }}
    steps:
      - name: convert
        id: convert
        run: |
          [[ ${{ github.ref_name }} == main ]] && ENV=prd || ENV=dev
          echo $ENV
          echo "env=${ENV}" >> $GITHUB_OUTPUT

  test:
    needs: convert_env
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ needs.convert_env.outputs.env }}

  step1:
    needs: convert_env
    uses: ./.github/workflows/step1.yaml
    with:
      env: ${{ needs.convert_env.outputs.env }}

  step2:
    needs: step1
    uses: ./.github/workflows/step2.yaml
    with:
      env: ${{ needs.convert_env.outputs.env }}

  debug:
    runs-on: ubuntu-latest
    needs: [step1, step2]
    steps:
      - name: echo
        run: echo ${{ needs.convert_env.outputs.env }}
