name: step1

on:
  workflow_call:
    inputs:
      env:
        description: 'env name'
        required: true
        type: string

  workflow_dispatch:
    inputs:
      env:
        description: 'env name'
        required: true
        default: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: echo branch name
      run: |
        git branch --show-current
        
    - name: hello
      run: echo Hello
  
    - name: world
      run: echo World
      
    - name: echo env
      run: ${{ github.event.inputs.env }}
