name: step1

on:
  workflow_run:
    workflows: [
      "workflow_run_start",
      "push_start",
    ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: echo branch name
      run: |
        echo ${{ github.event.workflow_run.head_branch }} 
        git branch --show-current

    - name: hello
      run: echo Hello
  
    - name: world
      run: echo World
      
