name: step2

on:
  workflow_run:
    workflows: ["step1"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: echo branch name
      run: |
        git checkout ${{ github.event.workflow_run.head_branch }}
        git branch --show-current

    - name: hello
      run: echo Hello

    - name: world
      run: echo World
      
