name: workflow_run_step1

on:
  workflow_run:
    workflows: ["workflow_run_start"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: hello
      run: echo Hello
  
    - name: world
      run: echo World
      
