name: workflow_run_start

on:
  workflow_dispatch:

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: echo branch name
      run: git branch --show-current

    - uses: ./.github/workflows/step1.yaml
    - uses: ./.github/workflows/step2.yaml
  